language: python
python:
  - "2.7"
notifications:
  email:
    on_success: never
    on_failure: always
install:
  - pip install coverage
script: nosetests -v --with-coverage --cover-package=torrentinfo test/tests.py