language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
notifications:
  email:
    recipients:
      - fuuzetsu@fuuzetsu.co.uk
    on_success: never
    on_failure: always
install:
  - pip install coverage
  - pip install argparse
script: nosetests -v --with-coverage --cover-package=torrentinfo test/tests.py