language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
notifications:
  email:
    recipients:
      - fuuzetsu@fuuzetsu.co.uk
    on_success: never
    on_failure: always
  irc:
    channels:
      - "irc.freenode.net#fuuzetsu"
install:
  - pip install coverage
  - pip install argparse
script: nosetests -v --with-coverage --cover-package=torrentinfo test/tests.py